// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test1() {
    driver.get("http://127.0.0.1:8000/");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    driver.findElement(By.cssSelector(".col-lg-1-5:nth-child(1) #add-to-cart-btn > .fi-rs-shopping-cart")).click();
    driver.findElement(By.cssSelector(".header-action-right:nth-child(2) .mini-cart-icon > img")).click();
    driver.findElement(By.linkText("Proceed To CheckOut")).click();
    driver.findElement(By.name("lname")).click();
    driver.findElement(By.name("lname")).sendKeys("oukattou");
    driver.findElement(By.name("fname")).sendKeys("ayoub");
    driver.findElement(By.name("billing_address")).sendKeys("Al Izdihar immeuble Mandour A, Etage 1, Ap8");
    driver.findElement(By.name("city")).sendKeys("Marrakech");
    driver.findElement(By.name("zipcode")).sendKeys("40000");
    driver.findElement(By.name("phone")).sendKeys("0639552625");
    driver.findElement(By.name("email")).sendKeys("ayoubmad.ouka@gmail.com");
    driver.findElement(By.linkText("Finish Order")).click();
  }
}
